release 20170227

diff --git a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/dir2mod b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/dir2mod
--- a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/dir2mod
+++ b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/dir2mod
@@ -14,22 +14,21 @@ cat /proc/config.gz | gunzip | grep -q SQUASHFS_XZ && MODULEFORMAT=xzm || MODULE
 
 convert_dir2lzm()
 {
-echo "Converting DIRs to module:"
-for a in `ls -d $1/$3*`; do
+  echo "Converting DIRs to module:"
+  for a in `ls -d $1/$3*`; do
     mn=$(basename $a)
     echo -ne \\n"	converting $mn --> $mn.$MODULEFORMAT "\\n
     mkdir -p "$2/$MODULEFORMAT"
     fd="$2/$MODULEFORMAT/$mn.$MODULEFORMAT"
 
     dir2lzm "$a" "$fd"
-done
+  done
 }
 
 convert_dir2xzm()
 {
-convert_dir2lzm "$@"
+  convert_dir2lzm "$@"
 }
-
 
 #convert DIRs to LZMs nolzma
 # $1 = directory images
@@ -37,23 +36,20 @@ convert_dir2lzm "$@"
 # $3 = mask of dirname (ex. - "??-" )
 convert_dir2nolzm()
 {
-echo "Converting DIRs to module (no compression):"
-for a in `ls -d $1/$3*`; do
+  echo "Converting DIRs to module (no compression):"
+  for a in `ls -d $1/$3*`; do
     mn=$(basename $a)
     echo -ne \\n"	converting $mn --> $mn.$MODULEFORMAT (no compression)"\\n
     mkdir -p "$2/nocomp_$MODULEFORMAT"
     fd="$2/nocomp_$MODULEFORMAT/$mn.$MODULEFORMAT"
-
     dir2nolzm "$a" "$fd"
-done
+  done
 }
 
 convert_dir2noxzm()
 {
-convert_dir2nolzm "$@"
+  convert_dir2nolzm "$@"
 }
-
-
 
 #convert DIRs to ROMs 
 # $1 = directory images
@@ -61,8 +57,8 @@ convert_dir2nolzm "$@"
 # $3 = mask of dirname (ex. - "??-" )
 convert_dir2rom()
 {
-echo "Converting DIRs to ROMs:"
-for a in `ls -d $1/$3*`; do
+  echo "Converting DIRs to ROMs:"
+  for a in `ls -d $1/$3*`; do
     mn=$(basename $a)
     echo "	converting $mn --> $mn.rom"
     st=`du -s -m $a ` 
@@ -77,8 +73,7 @@ for a in `ls -d $1/$3*`; do
     umount "$2/roms/$mn"
     rm -rf "$2/roms/$mn"
 
-done
-
+  done
 }
 
 HELP()
@@ -94,30 +89,27 @@ HELP()
    echo
 }
 
-. /usr/lib/magos/scripts/liblinuxlive || exit 1
-
+. /usr/lib/magos/functions
 
 case $1 in
--h | --help )
-HELP ;;
+  -h | --help )
+  HELP ;;
 
---test )
-TEST ;;
+  --test )
+  TEST ;;
 
-* )
+  * )
+  cmd=$1
+  [ "$cmd" != "xzm" -a "$cmd" != "lzm" -a "$cmd" != "nolzm" -a "$cmd" != "noxzm" -a "$cmd" != "rom"  ] && cmd=
+  shift
 
-cmd=$1
-[ "$cmd" != "xzm" -a "$cmd" != "lzm" -a "$cmd" != "nolzm" -a "$cmd" != "noxzm" -a "$cmd" != "rom"  ] && cmd=
-shift
-
-if [ ! -d "$1" -o "$2" = "" -o "$cmd" = "" ]; then
+  if [ ! -d "$1" -o "$2" = "" -o "$cmd" = "" ]; then
     HELP
     exit 1
-fi
-
-convert_dir2$cmd "$@"
-if [ $? != 0 ]; then echo "error building modules "; exit 1; fi
-;;
+  fi
+  convert_dir2$cmd "$@"
+  if [ $? != 0 ]; then echo "error building modules "; exit 1; fi
+  ;;
 esac
 
 #convert_dir2rom "$1" "$2" "$3"
