added 2021 platform. Unsupported platforms removed.

diff --git a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/mkinitrd b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/mkinitrd
--- a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/mkinitrd
+++ b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/mkinitrd
@@ -11,24 +11,13 @@ ARCH=32
 [ -d /lib64 ] && ARCH=64
 MODULEFORMAT=xzm
 
-# libraries to be placed in initrd/lib (links)
-INIRAMDLIBS1="ld-linux.so.2 ld-linux-x86-64.so.2 linux-vdso.so.1 libblkid.so.1 libc.so.6 libdl.so.2 libgcc_s.so libpthread.so.0
-  librt.so.1 libuuid.so.1 libz.so.1 libm.so.6 liblzma.so.?"
-
-# libraries to be placed in initrd/usr/lib (links)
-INIRAMDLIBS2='libelf.so.1 libglib-2.0.so.0 liblzo2.so.2 libm.so.6 libpcre.so.0 libpopt.so.0 libsysfs.so.2 libpci.so.3 libkmod.so.2
-  libresolv.so.2 libnss_files.so.2 libnss_dns.so.2 libattr.so.1 libacl.so.1
-  libaal-1.0.so.? libcom_err.so.2 libe2p.so.2 libext2fs.so.2 libreadline.so.? libreiser* librepair-* libntfs.so.10
-  libstdc++.so.6 libntfs-3g.so.?? libply-splash-core.so.2 libply.so.2 libgthread-2.0.so.0 libutil.so.1
-  libncurses.so.5 libtermcap.so.2 libcap.so.2 libncursesw.so.? libcryptsetup.so.? libuuid.so.1 libgcrypt.so.?? libudev.so.1 libgpg-error.so.0 libdevmapper.so.*'
-
 # binaries for /bin
 INIRAMDBIN1="busybox.static lspci httpfs blkid blockdev"
 # binaries for /usr/bin
-INIRAMDBIN2='dosfsck fsck fsck.ext2 fsck.reiser4 reiserfsck rsync losetup ntfsfix mksquashfs unsquashfs
+INIRAMDBIN2='dosfsck fsck fsck.ext2 reiserfsck rsync losetup ntfsfix mksquashfs unsquashfs
   ntfs-3g.probe ntfs-3g fusermount  mount.fuse ulockmgr_server sshfs shred cat ls dialog loadkeys unrar curlftpfs cryptsetup'
 # optional binaries for /usr/bin
-INIRAMDBINOPT="resume"
+INIRAMDBINOPT="resume fsck.reiser4"
 
 INITRDMODULES='kernel/fs/aufs /kernel/fs/squashfs kernel/fs/fuse/fuse.
   kernel/fs/isofs kernel/fs/fat kernel/fs/ntfs kernel/fs/reiserfs kernel/fs/xfs
@@ -57,18 +46,21 @@ INITRDMODULESOPT='kernel/fs/ext4 kernel/fs/jbd2 kernel/drivers/scsi/sd_mod. kern
 INITRDNETWORKDRIVERS='3c59x e100 eepro100 e1000 hp100 ne2k-pci r8169 8139too 8139cp via-rhine forcedeth e2100 eepro eexpress pcnet32
    3c501 3c503 3c505 3c507 3c509 3c515 tg3 jme virtio_net atl1 atl1c atl2 igb alx'
 
+# add space (Mb) for ext2 system space losses
+RAMPLUSSIZE=3
+
 MYPATH="$(pwd)"
 INITRDFOLD=/tmp/mkinitrd-$$
 INITRDIMG=/tmp/initrd.img-$$
 MOUNTDIR=/tmp/mkinitrd_mountdir_$$
-RAM0SIZE=20000
 
 # Copy librarries
 # $1 - filename
 # $2 - destination dir
 function copy_lib()
 {
- [ -h $2/$1 ] && rm -f $2/`readlink $1 | awk -F/ '{ print $(NF)}'` $2/$1
+# echo copy_lib \"$1\" \"$2\"
+# [ -h $2/$1 ] && rm -f $2/`readlink $1 | awk -F/ '{ print $(NF)}'` $2/$1
  LIBFOUND=
  for a in /usr/lib64 /lib64 /usr/lib /lib ;do
     LIBFOUND=$(ls -1 $a/$1 2>/dev/null)
@@ -98,8 +90,7 @@ function copy_bin()
     cp -Lf $a/$1 $2 && break
  done
  if [ ! -x "$2/$1" ] ;then
-    echo $1 not found !
-    exit 1
+    echo " Warning: $1 not found"
  fi
 }
 
@@ -109,13 +100,35 @@ function copy_bin()
 function copy_mod()
 {
   mkdir -p $(dirname lib/modules/$2/$1)
-  cp -pHR /lib/modules/$2/$1* $(dirname lib/modules/$2/$1)
+  cp -pHR /lib/modules/$2/$1* $(dirname lib/modules/$2/$1) 2>/dev/null || echo " Warning: module $(basename $1) not found"
 }
 
 function usage()
 {
  echo -e "usage $0 <initrd-image> <kernel-version> \n example: $0 /boot/initrd-$(uname -r).img $(uname -r)"
  exit 1
+}
+
+function mknoddevs()
+{
+ for a in $(seq 1 $2) ;do
+   mknod dev/$1$a $3 $4 $(($5+$a))
+ done
+}
+
+function mknodhd()
+{
+ mknod dev/$1 $2 $3 $4
+ mknoddevs $1 15 $2 $3 $4
+}
+
+function mknodscsi()
+{
+ dn=0
+ for a in $1 ; do
+   mknodhd sd$a $2 $3 $dn
+   dn=$(($dn + 16))
+ done
 }
 
 [ "$1" = "" -o  "$1" = "--version" -o "$1" = "--help" -o "$1" = "--help"  ] && usage
@@ -153,64 +166,28 @@ cp -p /usr/lib/magos/scripts/liblinuxlive ./ || exit 1
 ln -sf bin sbin
 touch etc/{m,fs}tab
 
+
 echo "creating devices"
 mknod dev/console c 5 1
 mknod dev/fb0 c 29 0
 mknod dev/null c 1 3
 mknod dev/zero c 1 5
 mknod dev/ram b 1 1
-mknod dev/systty c 4 0
-mknod dev/tty c 5 0
 mknod dev/fuse c 10 229
 mknod dev/sr0 b 11 0
 mknod dev/sr1 b 11 1
-for i in 1 2 3 4 5 6; do
-  mknod dev/tty$i c 4 $i
-done
-mknod dev/hda b 3 0
-for i in $(seq 1 16) ;do
-    mknod dev/hda$i b 3 $i
-done
-mknod dev/hdb b 3 64
-for i in $(seq 1 16) ;do
-    mknod dev/hdb$i b 3 $(($i+64))
-done
-mknod dev/hdc b 22 0
-for i in $(seq 1 16) ;do
-    mknod dev/hdc$i b 22 $i
-done
-mknod dev/hdd b 22 64
-for i in $(seq 1 16) ;do
-    mknod dev/hdd$i b 22 $(($i+64))
-done
+mknod dev/systty c 4 0
+mknod dev/tty c 5 0
+mknoddevs tty 6 c 4 0
+mknod dev/loop b 7 0
+mknoddevs loop 127 b 7 0
+mknodhd hda b 3 0
+mknodhd hdb b 3 64
+mknodhd hdc b 22 0
+mknodhd hdd b 22 64
+mknodscsi "a b c d e f g h i j k l m n o p" b 8
+mknodscsi "q r s t u v w x y z" b 65
 
-dn=0
-for i in a b c d e f g h i j k l m n o p ; do
-  mknod dev/sd$i b 8 $dn
-  dn=$(($dn + 1))
-  for j in $(seq 1 15) ;do
-      mknod dev/sd$i$j b 8 $dn
-      dn=$(($dn + 1))
-  done
-done
-
-dn=0
-for i in q r s t u v w x y z ; do
-  mknod dev/sd$i b 65 $dn
-  dn=$(($dn + 1))
-  for j in $(seq 1 15) ;do
-      mknod dev/sd$i$j b 65 $dn
-      dn=$(($dn + 1))
-  done
-done
-
-echo "copying libraries"
-for a in $INIRAMDLIBS1 ;do
-  copy_lib $a lib || exit 1
-done
-for a in $INIRAMDLIBS2 ;do
-  copy_lib $a usr/lib || exit 1
-done
 echo "copying binaries"
 for a in $INIRAMDBIN1 ;do
   copy_bin $a bin || exit 1
@@ -221,42 +198,48 @@ done
 for a in $INIRAMDBINOPT ;do
   copy_bin $a usr/bin
 done
-
 mv bin/busybox.static bin/busybox || exit 1
 mv usr/bin/losetup usr/bin/losetup.real || exit 1
+if [ -x /bin/kmod ] ;then
+   cp -pf /bin/kmod  bin
+fi
+[ -f /usr/share/pci.ids ] && cp -f /usr/share/pci.ids      usr/share
+[ -d /usr/share/locale/ru_RU.UTF-8 ] && cp -pHR /usr/share/locale/ru_RU.UTF-8/* usr/share/locale/ru_RU.UTF-8
 
+echo "copying libraries"
+for a in bin/* ; do
+   ldd 2>/dev/null $a | awk '{print $1}' | sed 's=^.*/=='
+done | sort -u  > liblist
+cat liblist | while read a ;do
+  copy_lib $a lib || exit 1
+done
+ls -1 lib/*.so* | sed s=lib/== > liblist
+for a in usr/bin/* ; do
+   ldd 2>/dev/null $a | awk '{print $1}' | sed 's=^.*/=='
+done | sort -u | grep -vf liblist > usrliblist
+cat usrliblist | while read a ;do
+  copy_lib $a usr/lib || exit 1
+done
+rm -f liblist usrliblist
+
+echo "making links"
+if [ "$ARCH" = "64" ] ;then
+   ln -s lib lib64
+   ln -s lib usr/lib64
+fi
+ln -sf $(basename lib/libz.so.?)  lib/libz.so
 # build links to busybox's functions from busybox's own help text
 for i in $(bin/busybox --help | grep -v Copyright | grep , | tr , " "); do
    ln -s busybox bin/$i 2>/dev/null
 done
-
-if [ -x /bin/kmod ] ;then
-   cp -pf /bin/kmod  bin
+if [ -x bin/kmod ] ;then
    for a in lsmod rmmod insmod modinfo modprobe depmod ;do
       ln -sf kmod bin/$a
    done
 fi
-
-if [ "$ARCH" = "64" ] ;then
-   ln -s lib lib64
-   ln -s lib usr/lib64
-   cp -f /usr/lib64/libbdevid.so.* usr/lib   || exit 1
-   cp -f /usr/lib64/libnash.so.*   usr/lib   || exit 1
-   cp -f /lib64/libfuse.*          usr/lib   || exit 1
-   cp -f /lib64/libulockmgr.*      usr/lib   || exit 1
-else
-   cp -f /usr/lib/libbdevid.so.*   usr/lib   || exit 1
-   cp -f /usr/lib/libnash.so.*     usr/lib   || exit 1
-   cp -f /lib/libfuse.*            usr/lib   || exit 1
-   cp -f /lib/libulockmgr.*        usr/lib   || exit 1
-fi
-[ -f /usr/share/pci.ids ] && cp -f /usr/share/pci.ids      usr/share 
-[ -d /usr/share/locale/ru_RU.UTF-8 ] && cp -pHR /usr/share/locale/ru_RU.UTF-8/* usr/share/locale/ru_RU.UTF-8
-
 ln -sf ../usr/bin/mksquashfs   bin/mksquashfs || exit 1
 ln -sf ../usr/bin/unsquashfs   bin/unsquashfs || exit 1
 ln -sf ../usr/bin/ntfs-3g      bin/ntfsmount  || exit 1
-ln -sf libz.so.1  lib/libz.so           || exit 1
 ln -sf dosfsck    usr/bin/fsck.msdos    || exit 1
 ln -sf dosfsck    usr/bin/fsck.vfat     || exit 1
 ln -sf fsck.ext2  usr/bin/fsck.ext3     || exit 1
@@ -269,9 +252,6 @@ ln -sf /bin/ntfs-3g usr/bin/mount.ntfs-3g || exit 1
 echo "copying modules"
 for mod in $INITRDMODULES; do
   copy_mod $mod $KERNEL
-done
-for mod in $INITRDMODULESOPT; do
-  copy_mod $mod $KERNEL 2>/dev/null
 done
 
 echo "copying network modules"
@@ -308,10 +288,12 @@ create_module tmp_xzm drivers.$MODULEFORMAT || exit 1
 chmod ago-x drivers.$MODULEFORMAT
 rm -Rf tmp_xzm
 
-echo "creating empty image file for initrd"
-dd if=/dev/zero of=$INITRDIMG bs=1024 count=$RAM0SIZE >/dev/null 2>&1
-mkfs -t ext2 -F -m 0 -b 1024 -i 1024 $INITRDIMG >/dev/null 2>&1
-tune2fs -i 120m $INITRDIMG >/dev/null 2>&1
+RAM0SIZE=$(du -bs "$INITRDFOLD" | awk '{print $1}' | sed s/......$//)
+RAM0SIZE=$(($RAM0SIZE+$RAMPLUSSIZE))
+echo "creating empty image file (${RAM0SIZE}M) for initrd"
+dd if=/dev/zero of=$INITRDIMG bs=1M count=${RAM0SIZE} >/dev/null 2>&1
+bin/busybox mke2fs -F -m 0 -b 1024 -i 1024 $INITRDIMG >/dev/null 2>&1
+tune2fs -c 0 -e continue -i 0 -L initrd -r 1 $INITRDIMG >/dev/null 2>&1
 
 echo "creating empty directory $MOUNTDIR"
 rm -Rf $MOUNTDIR
