shfmt -i 4 -w u2xzm

diff --git a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm
--- a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm
+++ b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm
@@ -1,40 +1,39 @@
 #!/bin/bash
-# /usr/lib/magos/scripts/urpm2xzm 
+# /usr/lib/magos/scripts/urpm2xzm
 # Version : 2.0
 # Description: create XZM (pfs) module from RPM (& dependences)
 # Author : Anton Goroshkin <http://magos-linux.ru>
 # Author : Alexandr Betkher <http://magos-linux.ru>
 # Author : Mikhail Zaripov <http://magos-linux.ru>
 
-HLP () {
-echo "Usage:  $(basename $0) <$(basename $0) keys> <packages list>  -o mod.xzm --urpmi <keys for urpmi>"
-echo "             $(basename $0) module.xzm - rebuild module"
-echo "$(basename $0) keys:"
-echo "-h | --help - this help"
-echo "-l | --load - mount the module after creation"
-echo "-o | --name - name for the module"
-echo "-m | --mask - mask (egrep format) to select modules where $(basename $0) will search rpm db, default \".\""
-echo "--mask clean - special mask value "clean" to choose base magos modules only"
-echo "-r | --rpmdb -  save /var/lib/rpm/* in module (rpm data base)"
-echo "-u | --urpmidb - save /var/lib/urpmi/* in module"
-echo "-e | --erase - create a module whis +wh files (aufs shadows) after urpme packages"
-echo "-b | --rebuildable - save in module local rpms, it need to rebuild module"
-echo "-d | --bulddir  - working directory, default dir is in tmpfs. This parameter works with rebuild module too (must be after module name)"
-echo "-f | --fast - fast compression alg"
-echo "--steps  - run script in \"step by step\" mode"
-exit 
+HLP() {
+    echo "Usage:  $(basename $0) <$(basename $0) keys> <packages list>  -o mod.xzm --urpmi <keys for urpmi>"
+    echo "             $(basename $0) module.xzm - rebuild module"
+    echo "$(basename $0) keys:"
+    echo "-h | --help - this help"
+    echo "-l | --load - mount the module after creation"
+    echo "-o | --name - name for the module"
+    echo "-m | --mask - mask (egrep format) to select modules where $(basename $0) will search rpm db, default \".\""
+    echo "--mask clean - special mask value "clean" to choose base magos modules only"
+    echo "-r | --rpmdb -  save /var/lib/rpm/* in module (rpm data base)"
+    echo "-u | --urpmidb - save /var/lib/urpmi/* in module"
+    echo "-e | --erase - create a module whis +wh files (aufs shadows) after urpme packages"
+    echo "-b | --rebuildable - save in module local rpms, it need to rebuild module"
+    echo "-d | --bulddir  - working directory, default dir is in tmpfs. This parameter works with rebuild module too (must be after module name)"
+    echo "-f | --fast - fast compression alg"
+    echo "--steps  - run script in \"step by step\" mode"
+    exit
 }
 
-[ "$1" == "" -o "$1" == "--help" -o $(id -un) != "root" ]  && HLP 
+[ "$1" == "" -o "$1" == "--help" -o $(id -un) != "root" ] && HLP
 
-
-MASK="." #default mask (grep format) for modules in $mod_path to be mounted in new aufs
-urpmipars="" #default pars for urpmi
-packages="" #list of packages, all parameters from urpm2xzm cmdline without "-" or "--" are packages 
-rpmdb="no" #save or not rpm database in module
-urpmidb="no" #update and save or not urpmi db before install packages
-erase="no" # make module with installed packages or deleted packages (wh aufs shadows) 
-result="-1" # result must be changed to zero by script 
+MASK="."         #default mask (grep format) for modules in $mod_path to be mounted in new aufs
+urpmipars=""     #default pars for urpmi
+packages=""      #list of packages, all parameters from urpm2xzm cmdline without "-" or "--" are packages
+rpmdb="no"       #save or not rpm database in module
+urpmidb="no"     #update and save or not urpmi db before install packages
+erase="no"       # make module with installed packages or deleted packages (wh aufs shadows)
+result="-1"      # result must be changed to zero by script
 rebuildable="no" # save or not local rpm packages in module
 argslist="$@"
 EXT="xzm"
@@ -45,117 +44,129 @@ MKSQOPTS=""
 export PATH=/usr/lib/magos/scripts:$PATH
 buildDir=/tmp/$$-tmp
 mod_path=/mnt/live/memory/images
-if . /etc/initvars ; then
-	buildDir=${SYSMNT}/$$-tmp
-	mod_path=${SYSMNT}/bundles
+if . /etc/initvars; then
+    buildDir=${SYSMNT}/$$-tmp
+    mod_path=${SYSMNT}/bundles
 fi
 
 # to change default values via magos configs
-. /usr/lib/magos/os-config 
+. /usr/lib/magos/os-config
 . /etc/sysconfig/MagOS
 
-umount_aufs () {
-echo "Unmounting filesystems..."
-grep "$root_br"/  /proc/mounts | awk '{ print $2}' | sort -r | while read tm ;do
-      umount "$tm" 2>/dev/null
-done
-umount "$root_br" 2>/dev/null 
+umount_aufs() {
+    echo "Unmounting filesystems..."
+    grep "$root_br"/ /proc/mounts | awk '{ print $2}' | sort -r | while read tm; do
+        umount "$tm" 2>/dev/null
+    done
+    umount "$root_br" 2>/dev/null
 }
 
 crash_exit() {
-	umount_aufs
-	if [ "$2" -ne 0 ] ; then
-	echo -ne '\033[0;31m' ; echo "$1" ; echo -ne '\033[0m\n'
-	[ "$3" ] || exit $2 
-	fi
-} 
+    umount_aufs
+    if [ "$2" -ne 0 ]; then
+        echo -ne '\033[0;31m'
+        echo "$1"
+        echo -ne '\033[0m\n'
+        [ "$3" ] || exit $2
+    fi
+}
 
 clear_mod_br() {
-rm -rf "$mod_br/tmp" "$mod_br/var/tmp" "$mod_br"/var/cache/{urpmi,ldconfig} "$mod_br"/etc/{urpmi,ld.so.cache} "$mod_br"/var/lib/{menu} "$mod_br/usr/share/applications/mimeinfo.cache" "$mod_br"/.wh* 2>/dev/null
-find "$mod_br/usr/share/icons" -type f -name icon-theme.cache 2>/dev/null | xargs rm -f 
-rmdir "$mod_br"/{dev,proc,sys,lost+found} "$mod_br/var/cache" "$mod_br/var/lib" "$mod_br/var" "$mod_br/etc" 2>/dev/null
-# save or not databases
-[ "$rpmdb" == "no" ] &&  rm -rf "$mod_br"/var/lib/rpm
-[ "$urpmidb" == "no" ] &&  rm -rf "$mod_br"/var/lib/urpmi
+    rm -rf "$mod_br/tmp" "$mod_br/var/tmp" "$mod_br"/var/cache/{urpmi,ldconfig} "$mod_br"/etc/{urpmi,ld.so.cache} "$mod_br"/var/lib/{menu} "$mod_br/usr/share/applications/mimeinfo.cache" "$mod_br"/.wh* 2>/dev/null
+    find "$mod_br/usr/share/icons" -type f -name icon-theme.cache 2>/dev/null | xargs rm -f
+    rmdir "$mod_br"/{dev,proc,sys,lost+found} "$mod_br/var/cache" "$mod_br/var/lib" "$mod_br/var" "$mod_br/etc" 2>/dev/null
+    # save or not databases
+    [ "$rpmdb" == "no" ] && rm -rf "$mod_br"/var/lib/rpm
+    [ "$urpmidb" == "no" ] && rm -rf "$mod_br"/var/lib/urpmi
 }
 
 #get urpmi parameters
-if  echo $@ |grep -q "\-*urpmi .*" ; then
-    urpmipars="$(echo $@ |sed 's/^.*\-*urpmi//')"
-    argslist="$(echo $@ |sed 's/\-*urpmi.*$//')"
+if echo $@ | grep -q "\-*urpmi .*"; then
+    urpmipars="$(echo $@ | sed 's/^.*\-*urpmi//')"
+    argslist="$(echo $@ | sed 's/\-*urpmi.*$//')"
 fi
 
 #get packages list and urpm2xzm parameters
-for arg in $argslist
-do
-  case "${arg}" in
-    "-h" | "--help" ) HLP;;
-    "-l" | "--load" ) load="yes";;
-    "-n" | "-o" | "--name") name="yes";;
+for arg in $argslist; do
+    case "${arg}" in
+    "-h" | "--help") HLP ;;
+    "-l" | "--load") load="yes" ;;
+    "-n" | "-o" | "--name") name="yes" ;;
     "-m" | "--mask") mask="yes" ;;
     "-d" | "--builddir") bdir="yes" ;;
     "-r" | "--rpmdb") rpmdb="yes" ;;
     "-u" | "--urpmidb") urpmidb="yes" ;;
     "-e" | "--erase") erase="yes" ;;
-    "-f" | "--fast") MKSQOPTS=$MKSQFS_FASTALG ;; 
-    "-b" | "--rebuildable" ) rebuildable="yes" ;;
-    "--steps" ) steps="yes" ;;
-    "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; exit 1;;
-    *) if [ "${name}" = "yes" ]; then NAME="${arg}"
-        elif [ "${mask}" = "yes" ]; then MASK="${arg}"
-        elif [ "${bdir}" = "yes" ]; then buildDir="$(readlink -e ${arg})/$$-tmp"
+    "-f" | "--fast") MKSQOPTS=$MKSQFS_FASTALG ;;
+    "-b" | "--rebuildable") rebuildable="yes" ;;
+    "--steps") steps="yes" ;;
+    "-"*[A-Za-z]*)
+        echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2
+        exit 1
+        ;;
+    *)
+        if [ "${name}" = "yes" ]; then
+            NAME="${arg}"
+        elif [ "${mask}" = "yes" ]; then
+            MASK="${arg}"
+        elif [ "${bdir}" = "yes" ]; then
+            buildDir="$(readlink -e ${arg})/$$-tmp"
         else packages="${packages} ${arg}"; fi
-        name="no";  mask="no"; bdir="no" ;;
-  esac
+        name="no"
+        mask="no"
+        bdir="no"
+        ;;
+    esac
 done
 
 # rebuild modules
-if $(file $1 2>/dev/null |grep -q quashfs    ); then
-	mkdir -p $(dirname $buildDir)
-	echo "rebuilding ${1} in $buildDir"
-	u2xzm_current=$(realpath $0)
-	unsquashfs -d $buildDir  $1 -e /var/lib/urpm2xzm/* -n >/dev/null
-	mv $buildDir/var/lib/urpm2xzm/* $buildDir
-	rm -fr $buildDir/var
-	CPWD=$(pwd)
-	cd $buildDir
-	for mod in $(find ./  -type d -name "??*") ; do
-		$u2xzm_current  $(echo $(cat $mod/cmdline)) | tee ./urpm2xzm.out
-		module=$(cat ./urpm2xzm.out | tail -n1)
-		mv $CPWD/$(basename $module) $CPWD/$(basename $module).old  2>/dev/null
-		mv $module ${CPWD}/ 
-	done
-	cd $CPWD
-	rm -rf $buildDir
-	echo $CPWD/$(basename $module)
-	exit 
+if $(file $1 2>/dev/null | grep -q quashfs); then
+    mkdir -p $(dirname $buildDir)
+    echo "rebuilding ${1} in $buildDir"
+    u2xzm_current=$(realpath $0)
+    unsquashfs -d $buildDir $1 -e /var/lib/urpm2xzm/* -n >/dev/null
+    mv $buildDir/var/lib/urpm2xzm/* $buildDir
+    rm -fr $buildDir/var
+    CPWD=$(pwd)
+    cd $buildDir
+    for mod in $(find ./ -type d -name "??*"); do
+        $u2xzm_current $(echo $(cat $mod/cmdline)) | tee ./urpm2xzm.out
+        module=$(cat ./urpm2xzm.out | tail -n1)
+        mv $CPWD/$(basename $module) $CPWD/$(basename $module).old 2>/dev/null
+        mv $module ${CPWD}/
+    done
+    cd $CPWD
+    rm -rf $buildDir
+    echo $CPWD/$(basename $module)
+    exit
 fi
 
-#get path and name for out module  
-if [ $NAME ] ; then
-	del_prefix=""
-	if [ $(echo $NAME |awk -F. '{print $NF}') == "xzm" ] ; then 
-		PNAME=$(dirname $NAME)
-		NAME=$(basename $NAME)
-	else
-		PNAME="$NAME" ; unset NAME
-	fi
+#get path and name for out module
+if [ $NAME ]; then
+    del_prefix=""
+    if [ $(echo $NAME | awk -F. '{print $NF}') == "xzm" ]; then
+        PNAME=$(dirname $NAME)
+        NAME=$(basename $NAME)
+    else
+        PNAME="$NAME"
+        unset NAME
+    fi
 fi
-[ $NAME ]   || NAME=$(echo $packages |awk '{print $1}').xzm
+[ $NAME ] || NAME=$(echo $packages | awk '{print $1}').xzm
 [ $PNAME ] || PNAME=$(dirname $NAME)
-[ -d $PNAME ] || crash_exit "Directory \"$PNAME\" is not exists" 2 
+[ -d $PNAME ] || crash_exit "Directory \"$PNAME\" is not exists" 2
 
 #select 2 modules: 10-core, 43-x-utilites. Without 10-core do not work correct
 #may be need ^[0-8][0-8] to select all base modules, but it works :)
-[ "$MASK" == "clean" ]  && MASK="^[1,4][0-1]-"
+[ "$MASK" == "clean" ] && MASK="^[1,4][0-1]-"
 
-#show masked modules and exit 
-if [[ -z "${packages}" ]] ; then
-  echo "Masked Modules:"
-  ls $mod_path | egrep $MASK
-  echo ''
-  HLP
-  exit
+#show masked modules and exit
+if [[ -z "${packages}" ]]; then
+    echo "Masked Modules:"
+    ls $mod_path | egrep $MASK
+    echo ''
+    HLP
+    exit
 fi
 
 URPMITMP=${buildDir}/urpm2xzm
@@ -169,15 +180,15 @@ umount $mod_br 2>/dev/null && rm -f $mod_file
 rm -rf "$mod_br" "$root_br" 2>/dev/null
 mkdir -p "$mod_br" "$root_br"
 SPACE=$(LC_ALL=C df -BM "$URPMITMP" --output=avail | tail -1 | tr -d M) # free space in folder
-[ ! -z "$SPACE" ] && SPACE=$(echo "$SPACE""*80/100" | bc)        # 80% of free space in folder
+[ ! -z "$SPACE" ] && SPACE=$(echo "$SPACE""*80/100" | bc)               # 80% of free space in folder
 [ ! -z "$SPACE" -a -z "$URPMISPACE" ] && URPMISPACE="$SPACE"M
 [ -z "$URPMISPACE" ] && URPMISPACE=1024M
-dd if=/dev/zero of="$mod_file" bs=1 count=0 seek="$URPMISPACE" >/dev/null  && mkfs.ext2 "$mod_file" >/dev/null
+dd if=/dev/zero of="$mod_file" bs=1 count=0 seek="$URPMISPACE" >/dev/null && mkfs.ext2 "$mod_file" >/dev/null
 mount -o loop "$mod_file" "$mod_br" || crash_exit "Can't mount temporary image file" 3
 
 mount_br="$mod_br=rw"
 for a in $(ls $mod_path | egrep $MASK); do
-	echo $a
+    echo $a
     mount_br="$mount_br:$(readlink -f ${mod_path}/$a)=rr"
 done
 
@@ -189,91 +200,99 @@ for tm in {dev,proc,sys}; do
 done
 
 #get rpms list before installing, need to generate rpm list in /var/lib/rpm/modules/mod_name
-rpm -qa -r $root_br > $URPMITMP/rpm_qa_before
+rpm -qa -r $root_br >$URPMITMP/rpm_qa_before
 
 [ "$steps" ] && read -p "next step - urpmi" ecode
-if [ "$ecode" == "exit" ] ; then umount_aufs ; umount $mod_br ; exit ; fi 
+if [ "$ecode" == "exit" ]; then
+    umount_aufs
+    umount $mod_br
+    exit
+fi
 
-if [ "$erase" == "no" ] ; then
-  for pack in $packages ; do
-	#try to delete package before installing, it need to install package again 
-    /usr/sbin/urpme  --root="$root_br"  $pack 2>/dev/null
-  done
-  if [ "$urpmidb" == "yes" ]  ; then
-		/usr/sbin/urpmi.update -a --urpmi-root="$root_br"
-		/usr/sbin/urpmi  --root="$root_br"  --urpmi-root="$root_br"  $packages $urpmipars
-  else
-		/usr/sbin/urpmi  --root="$root_br"   $packages $urpmipars
-  fi
-  result=$?
-  urpm=urpmi
-  action=install
+if [ "$erase" == "no" ]; then
+    for pack in $packages; do
+        #try to delete package before installing, it need to install package again
+        /usr/sbin/urpme --root="$root_br" $pack 2>/dev/null
+    done
+    if [ "$urpmidb" == "yes" ]; then
+        /usr/sbin/urpmi.update -a --urpmi-root="$root_br"
+        /usr/sbin/urpmi --root="$root_br" --urpmi-root="$root_br" $packages $urpmipars
+    else
+        /usr/sbin/urpmi --root="$root_br" $packages $urpmipars
+    fi
+    result=$?
+    urpm=urpmi
+    action=install
 else
-  #delete packages, it need to make module width wh* aufs shadows
-  /usr/sbin/urpme --root="$root_br" $packages 2>/dev/null 
-  result=$?
-  urpm=urpme
-  action=erase
+    #delete packages, it need to make module width wh* aufs shadows
+    /usr/sbin/urpme --root="$root_br" $packages 2>/dev/null
+    result=$?
+    urpm=urpme
+    action=erase
 fi
 
 #get rpms list after installing
-rpm -qa -r $root_br > $URPMITMP/rpm_qa_end
+rpm -qa -r $root_br >$URPMITMP/rpm_qa_end
 
 umount_aufs
 clear_mod_br
 
-#save info into the module 
+#save info into the module
 mkdir -p $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")
 mkdir -p $mod_br/var/lib/rpm/modules/
-date > $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/date
-cat $SYSMNT/layer-base/0/VERSION > $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/MagOS
-cat $URPMITMP/rpm_qa_* |sort |uniq -u > $mod_br/var/lib/rpm/modules/$(basename "${NAME%.$EXT}")
+date >$mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/date
+cat $SYSMNT/layer-base/0/VERSION >$mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/MagOS
+cat $URPMITMP/rpm_qa_* | sort | uniq -u >$mod_br/var/lib/rpm/modules/$(basename "${NAME%.$EXT}")
 sed -i 's/\(.*\)/\1.rpm/g' $mod_br/var/lib/rpm/modules/$(basename "${NAME%.$EXT}")
 rm $URPMITMP/rpm_qa_*
 
 # change all path in $@  to local, need to rebuild
-last="_" 
-for a in $@ ; do
-	if [ -f "$a" -o "$(echo $a |awk -F. '{print $NF}')_" == "xzm_" ] ; then 
-		basename $a 
-	elif [ -d "$a" -a $last == "-o" ] ; then
-		echo "./"
-	else
-		echo "$a" 
-	fi
-last="$a"	
-done 	> $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/cmdline
+last="_"
+for a in $@; do
+    if [ -f "$a" -o "$(echo $a | awk -F. '{print $NF}')_" == "xzm_" ]; then
+        basename $a
+    elif [ -d "$a" -a $last == "-o" ]; then
+        echo "./"
+    else
+        echo "$a"
+    fi
+    last="$a"
+done >$mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/cmdline
 
-#save local rpms in module		
-if [ "$rebuildable" == "yes" ] ; then		
-		for b in $@ ; do
-			[ -f "$b" -a "$(echo $b |awk -F. '{print $NF}')_" == "rpm_" ] && cp $b  $mod_br/var/lib/urpm2xzm/
-		done
-fi	
+#save local rpms in module
+if [ "$rebuildable" == "yes" ]; then
+    for b in $@; do
+        [ -f "$b" -a "$(echo $b | awk -F. '{print $NF}')_" == "rpm_" ] && cp $b $mod_br/var/lib/urpm2xzm/
+    done
+fi
 
 [ "$steps" ] && read -p "next step - mksquashfs" ecode
-if [ "$ecode" == "exit" ] ; then umount_aufs ; umount $mod_br ; exit ; fi 
+if [ "$ecode" == "exit" ]; then
+    umount_aufs
+    umount $mod_br
+    exit
+fi
 
-if [ "$result" -eq 0 -a "$erase" == "no" ] ; then
-	mksquashfs    $mod_br ${PNAME}/${NAME}  $MKSQOPTS -noappend  -regex -e ".wh..wh." && MODULE="$(readlink -e ${PNAME}/${NAME})" && create=OK
-elif [ "$result"  -eq 0 ] ; then
-	mksquashfs    $mod_br ${PNAME}/${del_prefix}${NAME}  $MKSQOPTS -noappend  && MODULE="$(readlink -e ${PNAME}/${del_prefix}${NAME})" && create=OK
+if [ "$result" -eq 0 -a "$erase" == "no" ]; then
+    mksquashfs $mod_br ${PNAME}/${NAME} $MKSQOPTS -noappend -regex -e ".wh..wh." && MODULE="$(readlink -e ${PNAME}/${NAME})" && create=OK
+elif [ "$result" -eq 0 ]; then
+    mksquashfs $mod_br ${PNAME}/${del_prefix}${NAME} $MKSQOPTS -noappend && MODULE="$(readlink -e ${PNAME}/${del_prefix}${NAME})" && create=OK
 else
     echo "Error $action packages: $packages"
-    [ $urpm == urpmi ] &&  echo "urpmi exitcode: \" $(man urpmi |grep -e "[[:space:]]${result}\.") \" "
+    [ $urpm == urpmi ] && echo "urpmi exitcode: \" $(man urpmi | grep -e "[[:space:]]${result}\.") \" "
     [ $urpm == urpme ] && echo "urpme exitcode: $result"
-    echo "Size of module source dir: $(du -ch  $mod_br |tail -n1 |cut -f 1)"
+    echo "Size of module source dir: $(du -ch $mod_br | tail -n1 | cut -f 1)"
     echo "Do you want to create the module, despite errors? [Y/N]"
-    read aaa ; [ $aaa ] || aaa=no
-    if [ $aaa == "Y" -o $aaa == "y" ] ; then 
-		mksquashfs    $mod_br ${PNAME}/${NAME}  -noappend  $MKSQOPTS && MODULE="$(readlink -e ${PNAME}/${NAME})" && create=OK
+    read aaa
+    [ $aaa ] || aaa=no
+    if [ $aaa == "Y" -o $aaa == "y" ]; then
+        mksquashfs $mod_br ${PNAME}/${NAME} -noappend $MKSQOPTS && MODULE="$(readlink -e ${PNAME}/${NAME})" && create=OK
     fi
 fi
 
-umount $mod_br && rm -rf  "$buildDir"
+umount $mod_br && rm -rf "$buildDir"
 
-if  [  $create  ] ; then
-	[ "$load" = "yes" ] && activate $MODULE >/dev/null && echo "Mounted successfully"
-	echo "$MODULE"
+if [ $create ]; then
+    [ "$load" = "yes" ] && activate $MODULE >/dev/null && echo "Mounted successfully"
+    echo "$MODULE"
 fi
-
