u2xzm fixes and futures

diff --git a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm
--- a/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm
+++ b/make_MagOS/files/patches/rootfs/MagOS/usr/lib/magos/scripts/u2xzm
@@ -14,11 +14,12 @@ echo "-h | --help - this help"
 echo "-l | --load - mount the module after creation"
 echo "-o | --name - name for the module"
 echo "-m | --mask - mask (egrep format) to select modules where $(basename $0) will search rpm db, default \".\" "
-echo "--mask clean - special mask value "clean" to choose base magos modules only"
+echo "--mask clean - specal mask value "clean" to choose base magos modules only"
 echo "-r | --rpmdb -  save /var/lib/rpm/* in module (rpm data base)"
 echo "-u | --urpmidb - save /var/lib/urpmi/* in module "
 echo "-e | --erase - create a module whis +wh files (aufs shadows) after urpme packages"
 echo "-b | --rebuildable - save in module local rpms, it need to rebuild module"
+echo "-d | --bulddir  - working directory, default dir is in tmpfs. This parameter works with rebuild module too (must be after module name) "
 echo "-f | --fast - fast compression alg"
 echo "--steps  - run script in "step by step" mode"
 exit 
@@ -26,56 +27,31 @@ exit
 
 [ "$1" == "" -o "$1" == "--help" -o $(id -un) != "root" ]  && HLP 
 
+
 MASK="." #default mask (grep format) for modules in $mod_path to be mounted in new aufs
 urpmipars="" #default pars for urpmi
 packages="" #list of packages, all parametrs from urpm2xzm cmdline without "-" or "--" are packages 
 rpmdb="no" #save or not rpm database in module
 urpmidb="no" #update and save 1or not urpmi db before install packages
 erase="no" # make module with installed packages or deleted packages (wh aufs shadows) 
-result="-1" # result must be changed to zero by script
-filter="??*" # filter to submodule in contaner to rebuild 
+result="-1" # result must be changed to zero by script 
 rebuidable="no" # save or not local rpm packages in module
 argslist="$@"
 EXT="xzm"
+MKSQOPTS=""
 
 #Work dirs
 export PATH=/usr/lib/magos/scripts:$PATH
-URPMITMP=/tmp/urpm2xzm
 buildDir=/tmp/$$-tmp
 mod_path=/mnt/live/memory/images
 if . /etc/initvars ; then
-	URPMITMP=${SYSMNT}/urpm2xzm
-	buildDir=${SYSMNT}/rebuild/$$-tmp
+	buildDir=${SYSMNT}/$$-tmp
 	mod_path=${SYSMNT}/bundles
 fi
-root_br="$URPMITMP/root"
-mod_br="$URPMITMP/changes"
-mod_file="$URPMITMP/urpm2xzm.img"
 
-# rebuild modules
-if $(file $1 2>/dev/null |grep -q quashfs    ); then
-	mkdir -p $(dirname $buildDir)
-	echo "rebuilding ${1}..."
-	u2xzm_current=$(realpath $0)
-	[ $2 ] && filter="$2"
-	unsquashfs -d $buildDir  $1 -e /var/lib/urpm2xzm/* -n >/dev/null
-	mv $buildDir/var/lib/urpm2xzm/* $buildDir
-	rm -fr $buildDir/var
-	CPWD=$(pwd)
-	cd $buildDir
-	for mod in $(find ./  -type d -name "$filter") ; do
-		cd $mod
-		$u2xzm_current  $(echo $(cat ./cmdline)) | tee ./urpm2xzm.out
-		module=$(cat ./urpm2xzm.out | tail -n1)
-		[ -f $CPWD/$(basename $module) ] && mv $CPWD/$(basename $module) $CPWD/$(basename $module).old
-		mv $module $CPWD
-		cd ..
-	done
-	cd $CPWD
-	rm -rf $buildDir
-	echo $CPWD/$(basename $module)
-	exit 
-fi
+# to change default values via magos configs
+. /usr/lib/magos/os-config 
+. /etc/sysconfig/MagOS
 
 umount_aufs () {
 echo "Unmounting filesystems..."
@@ -85,6 +61,14 @@ done
 umount "$root_br" 2>/dev/null 
 }
 
+crash_exit() {
+	umount_aufs
+	if [ "$2" -ne 0 ] ; then
+	echo -ne '\033[0;31m' ; echo "$1" ; echo -ne '\033[0m\n'
+	[ "$3" ] || exit $2 
+	fi
+} 
+
 clear_mod_br() {
 rm -rf "$mod_br/tmp" "$mod_br/var/tmp" "$mod_br"/var/cache/{urpmi,ldconfig} "$mod_br"/etc/{urpmi,ld.so.cache} "$mod_br"/var/lib/{menu} "$mod_br/usr/share/applications/mimeinfo.cache" "$mod_br"/.wh* 2>/dev/null
 find "$mod_br/usr/share/icons" -type f -name icon-theme.cache 2>/dev/null | xargs rm -f 
@@ -93,8 +77,6 @@ rmdir "$mod_br"/{dev,proc,sys,lost+found} "$mod_br/var/cache" "$mod_br/var/lib" 
 [ "$rpmdb" == "no" ] &&  rm -rf "$mod_br"/var/lib/rpm
 [ "$urpmidb" == "no" ] &&  rm -rf "$mod_br"/var/lib/urpmi
 }
- 
-. /usr/lib/magos/functions
 
 #get urpmi parametrs
 if  echo $@ |grep -q "\-*urpmi .*" ; then
@@ -110,21 +92,56 @@ do
     "-l" | "--load" ) load="yes";;
     "-n" | "-o" | "--name") name="yes";;
     "-m" | "--mask") mask="yes" ;;
+    "-d" | "--builddir") bdir="yes" ;;
     "-r" | "--rpmdb") rpmdb="yes" ;;
     "-u" | "--urpmidb") urpmidb="yes" ;;
     "-e" | "--erase") erase="yes" ;;
-    "-f" | "--fast") fast_alg="-f" ;; #not works yet
+    "-f" | "--fast") MKSQOPTS=$MKSQFS_FASTALG ;; 
     "-b" | "--rebuildable" ) rebuildable="yes" ;;
     "--steps" ) steps="yes" ;;
     "-"*[A-Za-z]*) echo "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" >&2; exit 1;;
     *) if [ "${name}" = "yes" ]; then NAME="${arg}"
         elif [ "${mask}" = "yes" ]; then MASK="${arg}"
+        elif [ "${bdir}" = "yes" ]; then buildDir="$(readlink -e ${arg})/$$-tmp"
         else packages="${packages} ${arg}"; fi
-        name="no";  mask="no";;
+        name="no";  mask="no"; bdir="no" ;;
   esac
 done
 
-[ $NAME ] || NAME=$(echo $packages |awk '{print $1}').xzm
+# rebuild modules
+if $(file $1 2>/dev/null |grep -q quashfs    ); then
+	mkdir -p $(dirname $buildDir)
+	echo "rebuilding ${1} in $buildDir"
+	u2xzm_current=$(realpath $0)
+	unsquashfs -d $buildDir  $1 -e /var/lib/urpm2xzm/* -n >/dev/null
+	mv $buildDir/var/lib/urpm2xzm/* $buildDir
+	rm -fr $buildDir/var
+	CPWD=$(pwd)
+	cd $buildDir
+	for mod in $(find ./  -type d -name "??*") ; do
+		$u2xzm_current  $(echo $(cat $mod/cmdline)) | tee ./urpm2xzm.out
+		module=$(cat ./urpm2xzm.out | tail -n1)
+		mv $CPWD/$(basename $module) $CPWD/$(basename $module).old  2>/dev/null
+		mv $module ${CPWD}/ 
+	done
+	cd $CPWD
+	rm -rf $buildDir
+	echo $CPWD/$(basename $module)
+	exit 
+fi
+
+#get path and name for out module  
+if [ $NAME ] ; then 
+	if [ $(echo $NAME |awk -F. '{print $NF}') == "xzm" ] ; then 
+		PNAME=$(dirname $NAME)
+		NAME=$(basename $NAME)
+	else
+		PNAME="$NAME" ; unset NAME
+	fi
+fi
+[ $NAME ]   || NAME=$(echo $packages |awk '{print $1}').xzm
+[ $PNAME ] || PNAME=$(dirname $NAME)
+[ -d $PNAME ] || crash_exit "Directory \"$PNAME\" is not exists" 2 
 
 #select 2 modules: 10-core, 43-x-utilites. Without 10-core do not work correct/
 #may be need ^[0-8][0-8] to select all base modules, but it works :)
@@ -139,6 +156,11 @@ if [[ -z "${packages}" ]] ; then
   exit
 fi
 
+URPMITMP=${buildDir}/urpm2xzm
+root_br="$URPMITMP/root"
+mod_br="$URPMITMP/changes"
+mod_file="$URPMITMP/urpm2xzm.img"
+
 umount_aufs
 umount $mod_br 2>/dev/null && rm -f $mod_file
 
@@ -149,7 +171,7 @@ SPACE=$(LC_ALL=C df -BM "$URPMITMP" --output=avail | tail -1 | tr -d M) # free s
 [ ! -z "$SPACE" -a -z "$URPMISPACE" ] && URPMISPACE="$SPACE"M
 [ -z "$URPMISPACE" ] && URPMISPACE=1024M
 dd if=/dev/zero of="$mod_file" bs=1 count=0 seek="$URPMISPACE" >/dev/null  && mkfs.ext2 "$mod_file" >/dev/null
-mount -o loop "$mod_file" "$mod_br" || exit 1
+mount -o loop "$mod_file" "$mod_br" || crash_exit "Can't mount temporary image file" 3
 
 mount_br="$mod_br=rw"
 for a in $(ls $mod_path | egrep $MASK); do
@@ -157,7 +179,7 @@ for a in $(ls $mod_path | egrep $MASK); do
     mount_br="$mount_br:$(readlink -f ${mod_path}/$a)=rr"
 done
 
-mount -t aufs -o br:"$mount_br" aufs "$root_br" || exit 3
+mount -t aufs -o br:"$mount_br" aufs "$root_br" || crash_exit "Can't mount aufs" 4
 
 mkdir -p $root_br/{dev,proc,sys,tmp}
 for tm in {dev,proc,sys}; do
@@ -168,7 +190,7 @@ done
 rpm -qa -r $root_br > $URPMITMP/rpm_qa_before
 
 [ "$steps" ] && read -p "next step - urpmi" ecode
-[ "$ecode" == "exit" ] && exit
+if [ "$ecode" == "exit" ] ; then umount_aufs ; umount $mod_br ; exit ; fi 
 
 if [ "$erase" == "no" ] ; then
   for pack in $packages ; do
@@ -203,46 +225,49 @@ cat $URPMITMP/rpm_qa_* |sort |uniq -u > $mod_br/var/lib/rpm/modules/$(basename "
 sed -i 's/\(.*\)/\1.rpm/g' $mod_br/var/lib/rpm/modules/$(basename "${NAME%.$EXT}")
 rm $URPMITMP/rpm_qa_*
 
-#save local rpms in module
-if [ "$rebuildable" == "yes" ] ; then
-	for a in $@ ; do [ -f $a ] && basename $a || echo $a ; done 	> $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/cmdline
-		for a in $@ ; do
-			[ -f $a ] && cp $a  $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/
-		done
+# change all path in module to local, need to rebuild
+last="_" 
+for a in $@ ; do
+	if [ -f "$a" -o "$(echo $a |awk -F. '{print $NF}')_" == "xzm_" ] ; then 
+		basename $a 
+	elif [ -d "$a" -a $last == "-o" ] ; then
+		echo "./"
 	else
-	echo $@ > $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/cmdline
-fi
+		echo "$a" 
+	fi
+last="$a"	
+done 	> $mod_br/var/lib/urpm2xzm/$(basename "${NAME%.$EXT}")/cmdline
+
+#save local rpms in module		
+if [ "$rebuildable" == "yes" ] ; then		
+		for b in $@ ; do
+			[ -f "$b" -a "$(echo $b |awk -F. '{print $NF}')_" == "rpm_" ] && cp $b  $mod_br/var/lib/urpm2xzm/
+		done
+fi	
 
 [ "$steps" ] && read -p "next step - mksquashfs" ecode
-[ "$ecode" == "exit" ] && exit
+if [ "$ecode" == "exit" ] ; then umount_aufs ; umount $mod_br ; exit ; fi 
 
 if [ "$result" -eq 0 -a "$erase" == "no" ] ; then
-  create_module $mod_br ${NAME} && MODULE="$(readlink -e ${NAME})" && create=OK
+	mksquashfs    $mod_br ${PNAME}/${NAME}  $MKSQOPTS -noappend  -regex -e ".wh..wh." && MODULE="$(readlink -e ${PNAME}/${NAME})" && create=OK
 elif [ "$result"  -eq 0 ] ; then
-  create_module $mod_br erase_${NAME} && MODULE="$(readlink -e erase_${NAME})" && create=OK
+	mksquashfs    $mod_br ${PNAME}/del_${NAME}  $MKSQOPTS -noappend  && MODULE="$(readlink -e ${PNAME}/del_${NAME})" && create=OK
 else
     echo "Error $action packages: $packages"
     [ $urpm == urpmi ] &&  echo "urpmi exitcode: \" $(man urpmi |grep -e "[[:space:]]${result}\.") \" "
     [ $urpm == urpme ] && echo "urpme exitcode: $result"
-    echo "size of module source dir: $(du -ch  $mod_br |tail -n1 |cut -f 1)"
-    echo "do you want to create the module, despite this? [Y/N]"
+    echo "Size of module source dir: $(du -ch  $mod_br |tail -n1 |cut -f 1)"
+    echo "Do you want to create the module, despite errors? [Y/N]"
     read aaa ; [ $aaa ] || aaa=no
     if [ $aaa == "Y" -o $aaa == "y" ] ; then 
-		create_module $mod_br ${NAME} && MODULE="$(readlink -e ${NAME})" && create=OK
+		mksquashfs    $mod_br ${PNAME}/${NAME}  -noappend  $MKSQOPTS && MODULE="$(readlink -e ${PNAME}/${NAME})" && create=OK
     fi
 fi
 
-umount $mod_br 
-
-rm -rf $mod_br 
-rm -rf $mod_file
-rm -rf $root_br 
-
-[ -h "$URPMITMP" ] || rmdir "$URPMITMP"
+umount $mod_br && rm -rf  "$buildDir"
 
 if  [  $create  ] ; then
 	[ "$load" = "yes" ] && activate $MODULE >/dev/null && echo "Mounted successfully"
 	echo "$MODULE"
 fi
-
 
