prerelease 20120623

diff --git a/make_modules/source/functions b/make_modules/source/functions
--- a/make_modules/source/functions
+++ b/make_modules/source/functions
@@ -63,25 +63,29 @@ function unpack()
   EXT=$(echo $EXT | tr A-Z a-z)
   echo $FNAME | grep -q [.]tar[.] &&  EXT=${FNAME/*.tar./tar.}
   mkdir -p "$DDIR"
+  cd "$DDIR"
   case "$EXT" in
   run)
       bash "$FNAME" $@ || die "unpack: error in $FNAME $@"
       ;;
   tgz|tar.gz)
-      tar -C "$DDIR" $@ -xf "$FNAME" >/dev/null || die "unpack: untar error"
+      tar $@ -xf "$FNAME" >/dev/null || die "unpack: untar error"
       ;;
   zip)
-      unzip -qd "$DDIR" $@ "$FNAME" || die "unpack: unzip error"
+      unzip -q $@ "$FNAME" || die "unpack: unzip error"
       ;;
   rar)
-      unrar x -inul  $@ "$FNAME" "$DDIR" || die "unpack: unrar error"
+      unrar x -inul  $@ "$FNAME" || die "unpack: unrar error"
       ;;
   rpm)
-      rpm2cpio "$FNAME" | cpio -i --make-directories "$DDIR" || die "unpack: rpm2cpio error"
+      rpm2cpio "$FNAME" | cpio -i -d || die "unpack: rpm2cpio error"
+      mkdir -p var/lib/rpm/modules
+      echo "${FNAME##*/}" >> var/lib/rpm/modules/module-$NAME
       ;;
   *)
       die "unpack: cant unpack $FNAME - unknown type $EXT"
   esac
+  cd "$MDIR"
 }
 
 function pack()
