add cXdialog & bugs fix

diff --git a/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/sbin/dir2mod b/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/sbin/dir2mod
--- a/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/sbin/dir2mod
+++ b/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/sbin/dir2mod
@@ -7,7 +7,7 @@
 
 
 
-#convert DIRs to LZMs nolzma 
+#convert DIRs to LZMs
 # $1 = directory images
 # $2 = directory of LZMs
 # $3 = mask of dirname (ex. - "??-" )
@@ -25,13 +25,13 @@ done
 }
 
 
-#convert DIRs to LZMs 
+#convert DIRs to LZMs nolzma
 # $1 = directory images
 # $2 = directory of LZMs
 # $3 = mask of dirname (ex. - "??-" )
 convert_dir2nolzm()
 {
-echo "Converting DIRs to ROMs:"
+echo "Converting DIRs to LZMs nocompression:"
 for a in `ls -d $1/$3*`; do
     mn=$(basename $a)
     echo -ne \\n"	converting $mn --> $mn.lzm (no compression)"\\n
@@ -103,10 +103,10 @@ if [ ! -d "$1" -o "$2" = "" -o ! "$cmd" = "lzm" -o ! "$cmd" = "nolzm" -o ! "$cmd
 fi
 
 convert_dir2$cmd "$@"
+if [ $? != 0 ]; then echo "error building modules "; exit 1; fi
 ;;
 esac
 
 #convert_dir2rom "$1" "$2" "$3"
 #convert_dir2sqm "$1" "$2" "$3"
 
-if [ $? != 0 ]; then echo "error building modules "; exit 1; fi
