installator fixes

diff --git a/make_MagOS/files/patches/rootfs/MagOS/usr/share/magos/modmnger/virtualize b/make_MagOS/files/patches/rootfs/MagOS/usr/share/magos/modmnger/virtualize
--- a/make_MagOS/files/patches/rootfs/MagOS/usr/share/magos/modmnger/virtualize
+++ b/make_MagOS/files/patches/rootfs/MagOS/usr/share/magos/modmnger/virtualize
@@ -4,11 +4,22 @@ error () {
 	sleep 2
 	exit $2
 	}
+efi=no; force=no
+for arg in $@ ;do
+  case "${arg}" in
+    "-e" | "--efi") efi="yes";;
+    "-f" | "--force") forse="yes";;
+    "-"*[A-Za-z]*) error "$(basename "$0"): invalid option -- '$(echo ${arg} | tr -d '-')'" 7;;
+    *) Vdisk="{arg}";;
+  esac
+done
 
-[ -z "$1" ] && error "need one arg" 2
+[ -z "$Vdisk" ] && error "need one arg" 2
 [ $(id -un) != "root" ]  && error "must be root"  3 
-[ $(free -g |grep Mem |awk '{print $2}') -le 3 ] &&  error "not enough memory" 4
 
+if ! [ $force ] ; then
+[ $(free -g |grep Mem |awk '{print $2}') -lt 3 ] && error "not enough memory" 4
+fi
 
 if cat /proc/mounts |grep -q $1 ; then
 	echo "Trying to unmount disks..."
@@ -20,29 +31,35 @@ if cat /proc/mounts |grep -q $1 ; then
 	done
 fi
 
-
-disk="$1"
-vm="$(echo VM${disk} |sed 's/\//_/g')-$$"
+Vdisk="$1"
+vm="$(echo VM${Vdisk} |sed 's/\//_/g')-$$"
 file="/root/${vm}.vmdk"
 arch=$(uname -i)
 
 if [ "$arch" !=  "x86_64" ] ;then  
-pae=" --pae on "
-ostype=linux
+	pae=" --pae on "
+	ostype=linux
 else
-pae=""
-ostype=Linux_64
+	pae=""
+	ostype=Linux_64
 fi
 
 echo "disk - $disk"
 echo "VboxVM  - $vm"
 echo "file - $file"
 echo "arch - $arch"
+echo "efi - $efi "
 
-service virtualbox start 
+chown root:root /usr /usr/lib /usr/lib64 /usr/bin 2>/dev/null # fix user modules permission bugs
+
+service virtualbox restart 
 VBoxManage createvm --name "$vm" -register
 VBoxManage modifyvm "$vm" --memory 1024  --vram 64 --boot1 disk --acpi on  --ostype $ostype --sata on  --nic1 nat $pae  
-VBoxManage internalcommands createrawvmdk -filename "$file" -rawdisk "$disk"
+VBoxManage internalcommands createrawvmdk -filename "$file" -rawdisk "$Vdisk"
 VBoxManage storageattach "$vm" --storagectl  "SATA" --port 0 --device 0 --type hdd --medium $file
+if [ $efi == "yes" ] ;then 
+	echo "enable efi booting..."
+	VBoxManage modifyvm  "$vm" --firmware efi
+fi
 VBoxManage startvm "$vm"
 
