xautority and display variables export now in mdialog script

diff --git a/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/modem_connect b/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/modem_connect
--- a/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/modem_connect
+++ b/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/modem_connect
@@ -1,8 +1,8 @@
 #!/bin/bash
 export PATH=/usr/lib/magos/scripts:/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/lib/qt4/bin
-export DISPLAY=:0.0
+#export DISPLAY=:0.0
 export HOME=/root
-export XAUTHORITY=`/bin/ls -1 /var/run/xauth/* | /usr/bin/head -1`
+#export XAUTHORITY=`/bin/ls -1 /var/run/xauth/* | /usr/bin/head -1`
 INTERACTIVE=yes
 TIMEOUT=60
 INETAUTOUP=no
@@ -65,7 +65,7 @@ inetup()
 }
 
 [ "$INTERACTIVE" = "yes"  ] || exit 0
-[ ! -f "$XAUTHORITY" ] && echo "modem_connect: Can't connect to X server! " && exit 1
+[ ! -f "$XAUTHORITY" ] && echo "modem_connect: Can't connect to X server! " # && exit 1
 
 killall wvdial
 wvdialconf
diff --git a/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/shownetstat b/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/shownetstat
--- a/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/shownetstat
+++ b/make_MagOS/files/patches/rootfs/rootfs/usr/lib/magos/udev/shownetstat
@@ -1,7 +1,7 @@
 #!/bin/bash
-export DISPLAY=:0.0
+#export DISPLAY=:0.0
 export HOME=/root
-export XAUTHORITY=`/bin/ls -1 /var/run/xauth/* | /usr/bin/head -1` 
+#export XAUTHORITY=`/bin/ls -1 /var/run/xauth/* | /usr/bin/head -1` 
 export PATH=/usr/lib/magos/scripts:/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/lib/qt4/bin
 INTERACTIVE=yes
 STAT=yes
@@ -9,13 +9,13 @@ STAT=yes
 . /etc/sysconfig/modem
 
 [ "$INTERACTIVE" = "yes" ] || exit 0
-[ ! -f "$XAUTHORITY" ] && echo "shownetstat: Can't connect to X server! " && exit 1
+[ ! -f "$XAUTHORITY" ] && echo "shownetstat: Can't connect to X server! " # && exit 1
 
 if [ "$STAT" == "yes" ] ; then
    total=`vnstat -i ppp0 | awk '/total:/{print $8 " " $9}'`
    today=`vnstat -i ppp0 | awk '/today/{print $8 " " $9}'`
    vnstat -r --disable -i $NEWIF
    service vnstat restart > /dev/null
-   mdialog --msgbox "Total - $total \n today - $today"
+   mdialog --msgbox "Total - $total \n today - $today" || exit 1
 fi
 exit 0
